name: CI

on:
  push:
  pull_request:

jobs:
  run-tests:
    name: Test
    strategy:
      fail-fast: 
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: 
          - 3.8
          - 3.9
          - 3.11
    runs-on: ${{martix.os}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install dependencies
        run: python -m pip install pytest .

      - name: Run tests
        run: pytest
